const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://www.inspiredtaste.net/wp-content/uploads/2016/07/Pancake-Recipe-2-1200.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'Italian Food',
      category: 'lunch',
      price: 13.99,
      img: 'https://images.unsplash.com/photo-1588360768052-f9450e13dc69?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bHVuY2glMjBmb29kfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'Cocolate Milk Shake',
      category: 'shakes',
      price: 6.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWcgpn7NrxUljYvgYT8njJXREokCxh_s6i6A&usqp=CAU',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Lunch_at_Pihka_Lintulahti.jpg/220px-Lunch_at_Pihka_Lintulahti.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.acouplecooks.com/wp-content/uploads/2020/12/How-to-Make-Eggs-Sunny-Side-Up-051.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://static.toiimg.com/photo/78237787/78237787.jpg?v=3',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbtxhOOrzMIh-E0PiqnIZ7auSZD5cAdQhRhg&usqp=CAU',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/HummusBowl-65a0050.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://www.simplyrecipes.com/thmb/NHjvu9hgIJhsRgd6HugeT7pSgPA=/440x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Shamrock-Shake-LEAD-3-3deb1e1f26364069a000847878a3f081.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: 'Orange juice',
      category: 'juice',
      price: 16.99,
      img: 'https://static.toiimg.com/thumb/msid-68562297,width-800,height-600,resizemode-75,imgsize-950123,pt-32,y_pad-40/68562297.jpg',
      desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic non soluta voluptatum accusantium? A delectus esse ab molestiae culpa. Hic aliquam magnam quaerat ipsa eligendi, reprehenderit at quasi maiores fuga'
    },
    {
      id: 11,
      title: 'Banana juice',
      category: 'juice',
      price: 16.99,
      img: 'https://static.toiimg.com/thumb/83832373.cms?width=1200&height=900',
      desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic non soluta voluptatum accusantium? A delectus esse ab molestiae culpa. Hic aliquam magnam quaerat ipsa eligendi, reprehenderit at quasi maiores fuga'
    },
  ];
  export default menu;